fixtures:
  symlinks:
    kubernetes: "#{source_dir}/../kubernetes"
    tarmak: "#{source_dir}/../tarmak"
    stdlib: "#{source_dir}/../stdlib"
    concat: "#{source_dir}/../concat"
    archive: "#{source_dir}/../archive"
    calico: "#{source_dir}/../calico"
    etcd: "#{source_dir}/../etcd"
    aws_ebs: "#{source_dir}/../aws_ebs"
    vault_client: "#{source_dir}/../vault_client"
    vault_server: "#{source_dir}/../vault_server"
    airworthy: "#{source_dir}/../airworthy"
